global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 2m

scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['172.31.87.98:19090']
        labels:
          service: 'server'

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['172.31.87.98:19091']
        labels:
          service: 'gateway'

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['172.31.89.4:19092']
        labels:
          service: 'auth'

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['172.31.89.4:19093']
        labels:
          service: 'user'

  - job_name: 'commerce-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['172.31.94.162:19094']
        labels:
          service: 'commerce'

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['172.31.94.162:19095']
        labels:
          service: 'payment'

  - job_name: 'delivery-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['172.31.83.125:19096']
        labels:
          service: 'delivery'

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['172.31.83.125:19097']
        labels:
          service: 'notification'
